### ISSUE TITLE
program Pong w fullscreen/ na srodku ekranu

### ISSUE THREAD

**Issue by outlaw1985** [abixadamj/helion-python#3]
przeprowadziłem program Pong bez większych problemów. natomiast jego realizacja odbywa się w dolnym prawym rogu ekranu i pół programu jest poza widokiem. dokumentacja pgzero oraz Pygame nie ma zastosowania (nie dziala w ogóle lub nie uruchamia gry w zależności od miejsca w kodzie) czy ktoś mógłby naprowadzić mnie jak ten problem rozwiązać?

**Comment by abixadamj** [comment]
A możesz pokazać screeny? Bo z opisu moja szklana kula nic nie chce powiedzieć... I podaj parametry obrazu, jaki masz (rozdzielczość) i podaj wartości `WIDTH` i `HEIGHT`

**Comment by outlaw1985** [comment]
![image](https://user-images.githubusercontent.com/92580155/145057510-d445542e-de63-4401-ac8c-52774a51b13d.pn

**Comment by outlaw1985** [comment]
![1](https://user-images.githubusercontent.com/92580155/145058415-dcfbd558-c12e-4987-8081-bcec4f083dc8.jpg)
![2](https://user-images.githubusercontent.com/92580155/145058418-e46ee82f-2d6c-4a7d-8ccf-a53ef2811888.jpg)

kod jest dokładnie taki jaki autor książki wskazał, nic w nim nie zmieniałem. Po prostu zastanawiam się gdzie w kodzie jest rozpisana "pozycja x,y" programu względem ekranu komputera. dodam, że na kilku komputerach sprawdziłem i wszystkie mają tę sam "objaw prawego rogu" bez wzgledu na rozdzielczość ekranu. 

```
import pgzrun
import pygame

TITLE = "Hello World"

WIDTH  = xxx
HEIGHT = yyy

def draw():
    screen.surface = pygame.display.set_mode((WIDTH, HEIGHT), pygame.FULLSCREEN)

pgzrun.go()

```
Tę instrukcję dostarcza dokumentacja Pygame ale również nie daje ona rozwiązania jak napisałem w pierwszym poście. pozdrawiam

**Comment by abixadamj** [comment]
Niestety nie wiem, gdzie i czy w ogóle w PygameZero można to ustawić. U mnie w Linux okno gry pojawia się idealnie całe od razu i nawet nie wiedziałem, że taka sytuacja może mieć miejsce.
![Zrzut ekranu z 2021-12-08 10-41-23](https://user-images.githubusercontent.com/5088643/145185807-9b55605e-d22e-432c-9a52-ed71d5499368.png)

Znalazłem kilka artykułów, np.: https://stackoverflow.com/questions/64253232/is-there-a-short-way-to-get-and-set-the-window-position-in-pygame 
Lecz to wszystko odnosi się do "pełnej" biblioteki pygame... więc niestety może się okazać, że w Windows trzeba za każdym razem przesunąć okno samodzielnie.

**Comment by abixadamj** [comment]
Bo uwaga! Konstrukcja Pygame Zero wyklucza taki kod, jak próbowałeś zrobić - to po prostu nie zadziała.

**Comment by outlaw1985** [comment]
dziękuję za poświęcony czas. jeśli jednak cos się urodzi proszę o kontakt PW to ponownie otworzę wątek i poradzimy innym jak to zrobić ;) pozdrawiam
